# Generated by Django 4.0.1 on 2022-03-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_created_at_recipe_created_by_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="created_by",
            new_name="creator",
        ),
    ]
