# Generated by Django 4.0.1 on 2022-03-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_rename_created_by_recipe_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
