# Generated by Django 4.2.3 on 2023-07-07 21:14

import django.db.models.deletion
from django.db import migrations, models


def create_categories(apps, schema_editor):
    Category = apps.get_model("recipes", "Category")

    for i, name in enumerate(("Other", "Rice", "Grain", "Pasta", "Ramen", "Dough")):
        Category.objects.create(id=i, name=name)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0005_alter_recipe_description_alter_recipe_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "categories",
            },
        ),
        migrations.RunPython(create_categories, reverse_code=noop),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="recipes.category",
            ),
        ),
    ]
